spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sut
    password: sut123
    url: jdbc:mysql://139.155.15.166:3306/sut?characterEncoding=utf-8&serverTimezone=UTC

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
#    port: 19201 #正式环境

